# Generated by Django 4.2.2 on 2023-07-25 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
