# Generated by Django 4.2.2 on 2023-07-25 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilePic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(null=True, upload_to='')),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='profile_pic',
        ),
    ]
