# Generated by Django 4.2.2 on 2023-07-25 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0009_profilepic_remove_post_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilepic',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='profilepic',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='profilepic',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AddField(
            model_name='profilepic',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
